name: Build TermX Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install required SDK components
      run: |
        sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Upload output folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: termx-binaries
        path: output/
